### ISSUE TITLE
Using with different links for status and action

### ISSUE THREAD

**Issue by tommyd75** [campbellinos/homebridge-httplock#1]
**Hello, I was looking at getting this to work with two different links one that shows the status via json and another that just accepts lock or unlock links something like this for status......**

getLockCurrentState: function(callback) {
  
    this.log('getLockCurrentState');
    
    
    request('http://192.168.1.100/jsonapi.asp?action=getdevice&id=L1', function (error, resp, body) {
      if (!error) {
        var response = JSON.parse(body);
        var value = response['value'];
        callback(null,value);
      }
      else {
        callback(error);
      }
    });
    
  },

**and something like this for sending the command...**

setLockTargetState: function(lock, callback) {

    this.log('setLockTargetState: ' + lock);
    this.currentValue.LockTargetState = lock;
    
    switch (lock) {
      case 0:
      case false:  target = 'unlock'; break;
      case 1:
      case true:   target = 'lock';  break; 
      default:  
    }
    
    // comment callback and uncomment your code
    callback();
    
    
    this.log( "Rear door set to: " + target );
    request("http://192.168.1.100/RunEvent="+target);
    

    
  },

**I had this working with the older version of Hap-Nodejs (https://github.com/KhaosT/HAP-NodeJS)but I just switched over the the newer version of home bridge and trying to get this working again. Any help would be greatly appreciated.**

**Comment by tommyd75** [comment]
@campbellinos Would you be able to show me how to implement this but with just a status link and a target link?
Like I had done above, I don't need the password or certs or the lock ID or the battery levels.

**Comment by phpfs** [comment]
Hi @tommyd75!

It's actually pretty simple to do that:
```javascript
request.get({      
	agentOptions: {      
      ca: fs.readFileSync(this.rootCACert)      
    },      
    url: this.url, //Change here!      
    qs: { username: this.username, password: this.password, lockid: this.lockID }      
  },       
```
Just change ```this.url ``` to ``` "http://example.me/myendpoint"``` wherever you want :)

For your use case, it could look something like that:
```javascript
request.get({          
    url: "http://example.me/myendpoint"
  },       
```

Greetings, phpfs

**Comment by tommyd75** [comment]
@phpfs I have the status part working fine. 
Just trying to figure out how to send the commands to lock and unlock. 
I used to use a link like this. 
http://192.168.1.10/tenHsServer/tenHsServer.aspx?t=ab&f=RunEvent&d=lock

And I would change the last part to be something like 
"http://192.168.1.10/tenHsServer/tenHsServer.aspx?t=ab&f=RunEvent&d=" + target

**Comment by phpfs** [comment]
Hi @tommyd75!

Have a look at this part:
'''javascript
LockAccessory.prototype.setState = function(state, callback) {
  var lockState = (state == Characteristic.LockTargetState.SECURED) ? "locked" : "unlocked";

  this.log("Set state to %s", lockState);

  request.post({
	agentOptions: {
      ca: fs.readFileSync(this.rootCACert)
    },
    url: this.url,
    form: { username: this.username, password: this.password, lockid: this.lockID, state: lockState }
  }, function(err, response, body) {
...
}
'''

And just change it to this:
'''javascript
LockAccessory.prototype.setState = function(state, callback) {
  var lockState = (state == Characteristic.LockTargetState.SECURED) ? "locked" : "unlocked";

var targetState = (state == Characteristic.LockTargetState.SECURED) ? "lock" : "unlock"; //Change as required

  this.log("Set state to %s", lockState);

  request.post({
    url: "http://myexample.com/mylock/change.aspx?d=" + targetState
  }, function(err, response, body) {
...
}
'''

**Comment by tommyd75** [comment]
OK, that changes the state but crashes when it tries to read the current state, I think I need to change the last part where it's passing the body to have it erase the statusUrl instead.

This is what happens when it locks and unlocks. It's trying to read from the same link as the controlUrl I think.


[Sat Sep 24 2016 01:08:15 GMT-0500 (CDT)] [Rear Door Lock] Set state to locked
[Sat Sep 24 2016 01:08:15 GMT-0500 (CDT)] [Rear Door Lock] State change complete.
undefined:3
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at LockAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-httplock/index.js:79:23)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-httplock/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-httplock/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-httplock/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)

Here is my updated code................................


LockAccessory.prototype.setState = function(state, callback) {
  var lockState = (state == Characteristic.LockTargetState.SECURED) ? "locked" : "unlocked";

  var targetState = (state == Characteristic.LockTargetState.SECURED) ? "lock" : "unlock"; //Change as required

  this.log("Set state to %s", lockState);

  request ({
    url: this.controlurl + targetState
  }, function(err, response, body) {
if (!err && response.statusCode == 200) {
      this.log("State change complete.");


  
   
      // we succeeded, so update the "current" state as well
      var currentState = (state == Characteristic.LockTargetState.SECURED) ?
        Characteristic.LockCurrentState.SECURED : Characteristic.LockCurrentState.UNSECURED;
      
      this.lockservice
        .setCharacteristic(Characteristic.LockCurrentState, currentState);

      var json = JSON.parse(body);
      
      
      callback(null); // success
    }
    else {
      this.log("Error '%s' setting lock state. Response: %s", err, body);
      callback(err || new Error("Error setting lock state."));
    }
  }.bind(this));
},

LockAccessory.prototype.getServices = function() {
  return [this.lockservice,];
}

**Comment by tommyd75** [comment]
@phpfs never mind, I removed the "var json = JSON.parse(body);" and its perfect now!

Thank you!!!

**Comment by phpfs** [comment]
Hi @tommyd75!

Your problem was, that the locker plugin expects a json encoded response from the given url which it can then send to your iDevice.
By removing the mentioned line, you should also consider what you want to return.
A possible solution could be, to simply return the requested state (the parameter of the function).
Or if your url returns xml, you could also parse that to get a safe information about the lock state.

I hope this solves your issue!

Greetings, phpfs

( @campbellinos : This issue can be closed :) )
